### ISSUE TITLE
Bulk process frames error

### ISSUE THREAD

**Issue by dhstsw** [Maurdekye/training-picker#13]
* What exactly is wrong: i get an error (see below)
* How to recreate the problem: create a frameset, click the bulk process button.
* What you expected to happen vs what actually happened: to work ;)

* Operating system: W10
* Browser: Chrome

```
Traceback (most recent call last):
  File "H:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "H:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "H:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\stable-diffusion-webui\extensions\training-picker\scripts\training_picker.py", line 415, in bulk_process_button_click
    img = process_image(img, should_resize, outfill_setting, outfill_color, outfill_border_blur, outfill_n_clusters)
TypeError: on_ui_tabs.<locals>.process_image() missing 1 required positional argument: 'square_original'
```

**Comment by Maurdekye** [comment]
whoops, sorry about that!
fixed :)
