### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by ARandomUserFromGithub** [Maurdekye/training-picker#20]
I'm not exactly sure why, but while the videos are present in the addon's video directory, the script doesn't seem to find it.

**Comment by CRCODE22** [comment]
> I'm not exactly sure why, but while the videos are present in the addon's video directory, the script doesn't seem to find them. Console writes: "IndexError: list index out of range Extracting frames from TestVideo.mp4 Exception encountered while attempting to extract frames: [WinError 2] The system cannot find the file specified"
> 
> Also, when trying to select a pre-existing folder from the dropdown menu on the right, the interface is covered with red ERROR tags, and console gives this error: Traceback (most recent call last): File "C:\git\sdA1111\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict output = await app.blocks.process_api( File "C:\git\sdA1111\venv\lib\site-packages\gradio\blocks.py", line 982, in process_api result = await self.call_function(fn_index, inputs, iterator) File "C:\git\sdA1111\venv\lib\site-packages\gradio\blocks.py", line 824, in call_function prediction = await anyio.to_thread.run_sync( File "C:\git\sdA1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "C:\git\sdA1111\venv\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread return await future File "C:\git\sdA1111\venv\lib\site-packages\anyio_backends_asyncio.py", line 867, in run result = context.run(func, *args) File "C:\git\sdA1111\extensions\training-picker\scripts\training_picker.py", line 344, in frameset_dropdown_change return get_image_update() File "C:\git\sdA1111\extensions\training-picker\scripts\training_picker.py", line 327, in get_image_update return gr.Image.update(value=current_frame_set[current_frame_set_index].get()), current_frame_set_index+1, f"/{len(current_frame_set)}" IndexError: list index out of range

I have the same problem.

**Comment by jeepsaintchaos** [comment]
If you check the "closed" issues, there are several similar posts. As it turns out, the issue isn't that it can't find your video files, but that it can't find the "fffmpeg" files. Stick the fffmpeg exe somewhere on your Windows drive and then add it to PATH is what fixed the issue for me.

**Comment by Gavanater7** [comment]
how exactly do you do that? I have no coding skills.

**Comment by mcDandy** [comment]
I have the same problem. I have ffmpeg in path. (Oh only for user...)
Trying gui refresh...

Adding to system wide path does not fix it.  
![obrazek](https://github.com/Maurdekye/training-picker/assets/18588943/dc1519fa-4a9f-4f83-aef6-7d5c85684a77)

Trying gui refresh...

There should be clearer error message.
