### ISSUE TITLE
Error loading script

### ISSUE THREAD

**Issue by hornedpariah** [Maurdekye/training-picker#22]
on startup:

Error loading script: training_picker.py
Traceback (most recent call last):
  File "G:\Github 2\stable-diffusion-webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "G:\Github 2\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "G:\Github 2\stable-diffusion-webui\extensions\training-picker\scripts\training_picker.py", line 16, in <module>
    from modules.ui import create_refresh_button, folder_symbol
ImportError: cannot import name 'folder_symbol' from 'modules.ui' (G:\Github 2\stable-diffusion-webui\modules\ui.py)

I reinstalled both a1111 and the extension twice and still have this outcome

**Comment by eyeweaver** [comment]
I've had this same issue for several days now..

**Comment by Trahloc** [comment]
Same errors with a fresh install and first time using the extension

**Comment by Woisek** [comment]
Error still persists ...

**Comment by rockerBOO** [comment]
Same bug as #21

**Comment by coronet1127** [comment]
https://github.com/Maurdekye/training-picker/issues/21#issuecomment-1422456269

**Comment by rockerBOO** [comment]
Fixed now

**Comment by coronet1127** [comment]
good
